create table object_info (
	id serial primary key,
	position_x float8,
	position_y float8,
	position_z float8,
	normal_x float8,
	normal_y float8,
	normal_z float8,
	szwht_x float8,
	szwht_y float8,
	szwht_z float8,
	color varchar(255),
	generic_id_0 int,
	generic_name_0 varchar(255),
	generic_score_0 float8,
	generic_id_1 int,
	generic_name_1 varchar(255),
	generic_score_1 float8,
	generic_id_2 int,
	generic_name_2 varchar(255),
    generic_score_2 float8,
    generic_name_3 varchar(255),
	generic_score_3 float8,
	specific_id_0 int,
	specific_name_0 varchar(255),
	specific_score_0 float8,
	specific_id_1 int,
	specific_name_1 varchar(255),
	specific_score_1 float8,
	specific_id_2 int,
	specific_name_2 varchar(255),
	specific_score_2 float8,
	width int,
	height int,
	bgr bytea,
	features float8[],
	ros_timestamp float8
	);
